Update rollback docs
alphagov/govuk-kubernetes-cluster-user-docs pull request #44
Opened 2022-07-28 12:07 UTC by fredericfran-gds

Changes:
1. delete reference about rollbacks being applicable to `integration`
   only
2. add a section about re-enabling image updates

2022-07-28 13:31 UTC, jonathanglassman commented on source/manage-app/roll-back-app/index.html.md.erb
> +**Warning**
GOV.UK style is to only use bold format for UI text e.g. "Select __Submit__ to submit the report." Would recommend not using the word warning at all.

2022-07-28 13:34 UTC, jonathanglassman commented on source/manage-app/roll-back-app/index.html.md.erb
> +this can be enabled by following the procedure in the next section.
Would recommend re-writing to make active, like the rest of the content. I.e.

"When you manually trigger the deploy GitHub Action for an app, that will stop the automatic update of that app's images. You can re-enable the automatic image update by following the [documentation on re-enabling automatic image updates after manual deploys](#re-enabling-automatic-image-updates-after-manual-deploys).

2022-07-28 13:35 UTC, jonathanglassman commented on source/manage-app/roll-back-app/index.html.md.erb
> +## Re-enabling automatic image updates after manual deploys
New section LGTM

2022-07-28 13:36 UTC, jonathanglassman requested changes
Content looks good overall. Have suggested a couple of changes.

2022-07-29 08:44 UTC, fredericfran-gds commented on source/manage-app/roll-back-app/index.html.md.erb
> +**Warning**
ok will do

2022-07-29 08:44 UTC, fredericfran-gds commented on source/manage-app/roll-back-app/index.html.md.erb
> +this can be enabled by following the procedure in the next section.
will do, thanks

2022-07-29 08:44 UTC, fredericfran-gds commented on source/manage-app/roll-back-app/index.html.md.erb
> +## Re-enabling automatic image updates after manual deploys
thanks

2022-07-29 08:49 UTC, fredericfran-gds commented
@jonathanglassman if you could have a look, I made the changes you recommended. Thanks!

2022-07-29 09:04 UTC, jonathanglassman approved these changes

2022-07-29 09:05 UTC, merged